In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [ ]:
df = pd.read_csv("/content/titanic_data_updated.csv")
df.head()

   PassengerId Survived Pclass  ...     Fare Cabin  Embarked
0            1       no  third  ...   7.2500   NaN         S
1            2      yes  first  ...  71.2833   C85         C
2            3      yes  third  ...   7.9250   NaN         S
3            4      yes  first  ...  53.1000  C123         S
4            5       no  third  ...   8.0500   NaN         S

[5 rows x 12 columns]

# Outlier Detection

In [ ]:
df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

In [ ]:
X = df.drop(["Survived"], axis=1)
y = df['Survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
age_imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

age_imputer.fit(X_train[["Age"]])

X_train['Age'] = age_imputer.transform(X_train[["Age"]]).ravel()
X_test['Age'] = age_imputer.transform(X_test[['Age']])

embarked_imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
embarked_imputer.fit(X_train[['Embarked']])

# Transform both train and test data

X_train['Embarked'] = embarked_imputer.transform(X_train[['Embarked']]).ravel() # 2D ---> 1D
X_test['Embarked'] = embarked_imputer.transform(X_test[['Embarked']]).ravel() # 2D ---> 1D

### Using Z-Score

In [ ]:
mean_age = X_train['Age'].mean()
std_age = X_train['Age'].std()

X_train['zscore_age'] = (X_train['Age'] - mean_age) / std_age
X_train

     Pclass     Sex        Age  SibSp  Parch      Fare Embarked    zscore_age
331   first    male  45.500000      0      0   28.5000        S  1.231398e+00
733  second    male  23.000000      0      0   13.0000        S -5.001304e-01
382   third    male  32.000000      0      0    7.9250        S  1.924808e-01
704   third    male  26.000000      1      0    7.8542        S -2.692600e-01
813   third  female   6.000000      4      2   31.2750        S -1.808396e+00
..      ...     ...        ...    ...    ...       ...      ...           ...
106   third  female  21.000000      0      0    7.6500        S -6.540440e-01
270   first    male  29.498846      0      0   31.0000        S  2.734055e-16
860   third    male  41.000000      2      0   14.1083        S  8.850920e-01
435   first  female  14.000000      1      2  120.0000        S -1.192742e+00
102   first    male  21.000000      0      1   77.2875        S -6.540440e-01

[712 rows x 8 columns]

In [ ]:
outliers = X_train[abs(X_train['zscore_age']) > 3 ]
print(len(outliers))
display(outliers)

5

     Pclass   Sex   Age  SibSp  Parch    Fare Embarked  zscore_age
116   third  male  70.5      0      0   7.750        Q    3.155317
745   first  male  70.0      1      1  71.000        S    3.116839
630   first  male  80.0      0      0  30.000        S    3.886407
851   third  male  74.0      0      0   7.775        S    3.424666
672  second  male  70.0      0      0  10.500        S    3.116839

In [ ]:
mean_fare = X_train['Fare'].mean()
std_fare = X_train['Fare'].std()

X_train['zscore_fare'] = (X_train['Fare'] - mean_fare) / std_fare
X_train

     Pclass     Sex        Age  ...  Embarked    zscore_age  zscore_fare
331   first    male  45.500000  ...         S  1.231398e+00    -0.078628
733  second    male  23.000000  ...         S -5.001304e-01    -0.376880
382   third    male  32.000000  ...         S  1.924808e-01    -0.474533
704   third    male  26.000000  ...         S -2.692600e-01    -0.475896
813   third  female   6.000000  ...         S -1.808396e+00    -0.025232
..      ...     ...        ...  ...       ...           ...          ...
106   third  female  21.000000  ...         S -6.540440e-01    -0.479825
270   first    male  29.498846  ...         S  2.734055e-16    -0.030523
860   third    male  41.000000  ...         S  8.850920e-01    -0.355554
435   first  female  14.000000  ...         S -1.192742e+00     1.682019
102   first    male  21.000000  ...         S -6.540440e-01     0.860143

[712 rows x 9 columns]

In [ ]:
outliers = X_train[abs(X_train['zscore_fare']) > 3 ]
print(len(outliers))
display(outliers)

17

    Pclass     Sex        Age  ...  Embarked    zscore_age  zscore_fare
118  first    male  24.000000  ...         C -4.231736e-01     4.135780
716  first  female  38.000000  ...         C  6.542216e-01     3.751020
377  first    male  27.000000  ...         C -1.923032e-01     3.442666
742  first  female  21.000000  ...         C -6.540440e-01     4.421605
380  first  female  42.000000  ...         C  9.620488e-01     3.751020
779  first  female  43.000000  ...         S  1.039006e+00     3.439539
730  first  female  29.000000  ...         S -3.838960e-02     3.439539
88   first  female  23.000000  ...         S -5.001304e-01     4.433631
341  first  female  24.000000  ...         S -4.231736e-01     4.433631
557  first    male  29.498846  ...         C  2.734055e-16     3.751020
737  first    male  35.000000  ...         C  4.233512e-01     9.231235
679  first    male  36.000000  ...         C  5.003080e-01     9.231235
438  first    male  64.000000  ...         S  2.655098e+00     4.433631
689  first  female  15.000000  ...         S -1.115785e+00     3.439539
258  first  female  35.000000  ...         C  4.233512e-01     9.231235
27   first    male  19.000000  ...         S -8.079576e-01     4.433631
700  first  female  18.000000  ...         C -8.849144e-01     3.751020

[17 rows x 9 columns]

### Outliers with IQR

In [ ]:
# Age

age_q1 = X_train['Age'].quantile(0.25)
age_q3 = X_train['Age'].quantile(0.75)
age_IQR = age_q3 - age_q1

age_minimum = age_q1 - 1.5 * age_IQR
age_maximum = age_q3 + 1.5 * age_IQR

print(age_minimum, age_maximum)

2.5 54.5

In [ ]:
age_outliers = X_train[ (X_train['Age'] < age_minimum) | (X_train['Age'] > age_maximum)]

In [ ]:
print(len(age_outliers))
display(age_outliers)

54

     Pclass     Sex    Age  SibSp  ...      Fare  Embarked zscore_age  zscore_fare
326   third    male  61.00      0  ...    6.2375         S   2.424228    -0.507004
483   third  female  63.00      0  ...    9.5875         S   2.578141    -0.442543
7     third    male   2.00      3  ...   21.0750         S  -2.116223    -0.221500
305   first    male   0.92      1  ...  151.5500         S  -2.199336     2.289105
829   first  female  62.00      0  ...   80.0000         S   2.501185     0.912337
626  second    male  57.00      0  ...   12.3500         Q   2.116401    -0.389387
456   first    male  65.00      0  ...   26.5500         S   2.732055    -0.116150
172   third  female   1.00      1  ...   11.1333         S  -2.193180    -0.412799
164   third    male   1.00      4  ...   39.6875         S  -2.193180     0.136642
381   third  female   1.00      0  ...   15.7417         C  -2.193180    -0.324124
694   first    male  60.00      0  ...   26.5500         S   2.347271    -0.116150
587   first    male  60.00      1  ...   79.2000         C   2.347271     0.896943
570  second    male  62.00      0  ...   10.5000         S   2.501185    -0.424985
879   first  female  56.00      0  ...   83.1583         C   2.039444     0.973109
94    third    male  59.00      0  ...    7.2500         S   2.270314    -0.487522
11    first  female  58.00      0  ...   26.5500         S   2.193357    -0.116150
644   third  female   0.75      2  ...   19.2583         C  -2.212419    -0.256458
15   second  female  55.00      0  ...   16.0000         S   1.962487    -0.319154
530  second  female   2.00      1  ...   26.0000         S  -2.116223    -0.126733
340  second    male   2.00      1  ...   26.0000         S  -2.116223    -0.126733
487   first    male  58.00      0  ...   29.7000         C   2.193357    -0.055538
467   first    male  56.00      0  ...   26.5500         S   2.039444    -0.116150
827  second    male   1.00      0  ...   37.0042         C  -2.193180     0.085010
116   third    male  70.50      0  ...    7.7500         Q   3.155317    -0.477901
745   first    male  70.00      1  ...   71.0000         S   3.116839     0.739159
268   first  female  58.00      0  ...  153.4625         S   2.193357     2.325906
479   third  female   2.00      0  ...   12.2875         S  -2.116223    -0.390590
195   first  female  58.00      0  ...  146.5208         C   2.193357     2.192333
16    third    male   2.00      4  ...   29.1250         Q  -2.116223    -0.066602
469   third  female   0.75      2  ...   19.2583         C  -2.212419    -0.256458
630   first    male  80.00      0  ...   30.0000         S   3.886407    -0.049765
152   third    male  55.50      0  ...    8.0500         S   2.000966    -0.472128
684  second    male  60.00      1  ...   39.0000         S   2.347271     0.123413
119   third  female   2.00      4  ...   31.2750         S  -2.116223    -0.025232
297   first  female   2.00      1  ...  151.5500         S  -2.116223     2.289105
851   third    male  74.00      0  ...    7.7750         S   3.424666    -0.477420
183  second    male   1.00      2  ...   39.0000         S  -2.193180     0.123413
438   first    male  64.00      1  ...  263.0000         S   2.655098     4.433631
788   third    male   1.00      1  ...   20.5750         S  -2.193180    -0.231122
672  second    male  70.00      0  ...   10.5000         S   3.116839    -0.424985
386   third    male   1.00      5  ...   46.9000         S  -2.193180     0.275425
232  second    male  59.00      0  ...   13.5000         S   2.270314    -0.367259
824   third    male   2.00      4  ...   39.6875         S  -2.116223     0.136642
803   third    male   0.42      0  ...    8.5167         C  -2.237815    -0.463148
170   first    male  61.00      0  ...   33.5000         S   2.424228     0.017582
755  second    male   0.67      1  ...   14.5000         S  -2.218576    -0.348017
642   third  female   2.00      3  ...   27.9000         S  -2.116223    -0.090174
647   first    male  56.00      0  ...   35.5000         C   2.039444     0.056066
492   first    male  55.00      0  ...   30.5000         S   1.962487    -0.040144
555   first    male  62.00      0  ...   26.5500         S   2.501185    -0.116150
205   third  female   2.00      0  ...   10.4625         S  -2.116223    -0.425707
366   first  female  60.00      1  ...   75.2500         C   2.347271     0.820937
831  second    male   0.83      1  ...   18.7500         S  -2.206263    -0.266238
252   first    male  62.00      0  ...   26.5500         S   2.501185    -0.116150

[54 rows x 9 columns]

In [ ]:
# Fare

fare_q1 = X_train['Fare'].quantile(0.25)
fare_q3 = X_train['Fare'].quantile(0.75)
fare_IQR = fare_q3 - fare_q1

fare_minimum = max(0, fare_q1 - 1.5 * fare_IQR)
fare_maximum = fare_q3 + 1.5 * fare_IQR

print(fare_minimum, fare_maximum)

0 64.3625

In [ ]:
fare_outliers = X_train[ (X_train['Fare'] < fare_minimum) | (X_train['Fare'] > fare_maximum)]
print(len(fare_outliers))
display(fare_outliers)

96

     Pclass     Sex   Age  SibSp  ...      Fare  Embarked zscore_age  zscore_fare
118   first    male  24.0      0  ...  247.5208         C  -0.423174     4.135780
486   first  female  35.0      1  ...   90.0000         S   0.423351     1.104757
716   first  female  38.0      0  ...  227.5250         C   0.654222     3.751020
390   first    male  36.0      1  ...  120.0000         S   0.500308     1.682019
377   first    male  27.0      0  ...  211.5000         C  -0.192303     3.442666
..      ...     ...   ...    ...  ...       ...       ...        ...          ...
681   first    male  27.0      0  ...   76.7292         C  -0.192303     0.849400
385  second    male  18.0      0  ...   73.5000         S  -0.884914     0.787264
700   first  female  18.0      1  ...  227.5250         C  -0.884914     3.751020
435   first  female  14.0      1  ...  120.0000         S  -1.192742     1.682019
102   first    male  21.0      0  ...   77.2875         S  -0.654044     0.860143

[96 rows x 9 columns]

### Z-Sccore Outlier detection is better for age outliers.

*   Delete Outliers

In [ ]:
X_train = X_train[abs(X_train['zscore_age']) <= 3 ]
X_train

     Pclass     Sex        Age  ...  Embarked    zscore_age  zscore_fare
331   first    male  45.500000  ...         S  1.231398e+00    -0.078628
733  second    male  23.000000  ...         S -5.001304e-01    -0.376880
382   third    male  32.000000  ...         S  1.924808e-01    -0.474533
704   third    male  26.000000  ...         S -2.692600e-01    -0.475896
813   third  female   6.000000  ...         S -1.808396e+00    -0.025232
..      ...     ...        ...  ...       ...           ...          ...
106   third  female  21.000000  ...         S -6.540440e-01    -0.479825
270   first    male  29.498846  ...         S  2.734055e-16    -0.030523
860   third    male  41.000000  ...         S  8.850920e-01    -0.355554
435   first  female  14.000000  ...         S -1.192742e+00     1.682019
102   first    male  21.000000  ...         S -6.540440e-01     0.860143

[707 rows x 9 columns]

In [ ]:
minimum_zscore_fare = X_train[abs(X_train['zscore_fare']) <= 3]['Fare'].min()
print(minimum_zscore_fare)


max_zscore_fare = X_train[abs(X_train['zscore_fare']) <= 3]['Fare'].max()
print(max_zscore_fare)

0.0
164.8667

In [ ]:
X_train['Fare'] = X_train['Fare'].clip(fare_minimum, fare_maximum)
X_train['Fare'].max()

/tmp/ipykernel_8718/2216021471.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Fare'] = X_train['Fare'].clip(fare_minimum, fare_maximum)

64.3625