In [98]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.pipeline import Pipeline
import kagglehub
from kagglehub import KaggleDatasetAdapter

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score

# Q1.

In [99]:
df = kagglehub.dataset_load(KaggleDatasetAdapter.PANDAS, "uciml/iris", "Iris.csv")
df.sample(5)

Using Colab cache for faster access to the 'iris' dataset.

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
33,34,5.5,4.2,1.4,0.2,Iris-setosa
122,123,7.7,2.8,6.7,2.0,Iris-virginica
116,117,6.5,3.0,5.5,1.8,Iris-virginica
18,19,5.7,3.8,1.7,0.3,Iris-setosa
117,118,7.7,3.8,6.7,2.2,Iris-virginica

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [101]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [102]:
if "Id" in df.columns:
    df.drop('Id', axis=1, inplace=True)

label_encoder = LabelEncoder()

X = df.drop('Species', axis=1)
y= df['Species']

y = label_encoder.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2, stratify=y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [103]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
knn.predict(X_test)

array([0, 2, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 0, 0, 0, 1, 1, 2, 0, 2,
       1, 2, 2, 1, 1, 0, 2, 0])

In [104]:
# 7. Calculate the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy Score: {accuracy:.4f}\n")

# 8. Display the Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\n")

# 9. Generate the Classification Report
# We can pass the original string names to target_names so the report is easier to read!
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

Accuracy Score: 1.0000

Confusion Matrix:
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00        10
 Iris-virginica       1.00      1.00      1.00        10

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

# Q2.

In [105]:
df = kagglehub.dataset_load(KaggleDatasetAdapter.PANDAS, "imakash3011/customer-personality-analysis", "marketing_campaign.csv", pandas_kwargs={"sep": "\t"})
df.head()

Using Colab cache for faster access to the 'customer-personality-analysis' dataset.

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

In [106]:
df.dropna(inplace=True)

In [107]:
X = df.select_dtypes(['int64', 'float64']).drop(['Response', 'ID'], axis=1)
y = df['Response']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [108]:
knn_model_pipeline = Pipeline(
    steps=[
        ('scaler', StandardScaler()),
        ('knn', KNeighborsClassifier())
    ]
)
knn_model_pipeline.fit(X_train, y_train)
y_pred_default = knn_model_pipeline.predict(X_test)

In [109]:
param_grid = {
    "knn__n_neighbors" : range(3, 50),
    "knn__metric" : ['euclidean', 'manhattan', 'minkowski'],
    "knn__weights" : ['uniform', 'distance']
}



knn_best_model = GridSearchCV(
    estimator = knn_model_pipeline,
    param_grid = param_grid,
    cv=5
)

knn_best_model.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('knn', KNeighborsClassifier())]),
             param_grid={'knn__metric': ['euclidean', 'manhattan', 'minkowski'],
                         'knn__n_neighbors': range(3, 50),
                         'knn__weights': ['uniform', 'distance']})

In [110]:
best_knn_model = knn_best_model.best_estimator_
best_knn_model

Pipeline(steps=[('scaler', StandardScaler()),
                ('knn',
                 KNeighborsClassifier(metric='manhattan', n_neighbors=26,
                                      weights='distance'))])

In [111]:
y_pred_best = best_knn_model.predict(X_test)

In [130]:
def evaluate_model(y_true, y_preds, model_name):
    print(f"--- {model_name} Performance ---")
    print(f"Accuracy : {accuracy_score(y_true, y_preds):.4f}")

    # Using 'weighted' average handles potential class imbalances elegantly
    print(f"Precision: {precision_score(y_true, y_preds, average='weighted'):.4f}")
    print(f"Recall   : {recall_score(y_true, y_preds, average='weighted'):.4f}")
    print(f"F1-score : {f1_score(y_true, y_preds, average='weighted'):.4f}\n")


print(f"Best K: {knn_best_model.best_params_['knn__n_neighbors']}")
print(f"Best Metric: {knn_best_model.best_params_['knn__metric']}")
print(f"Best Weights: {knn_best_model.best_params_['knn__weights']}\n")


evaluate_model(y_test, y_pred_default, "Default KNN")
evaluate_model(y_test, y_pred_best, "Tuned KNN using GridSearchCV")

Best K: 26
Best Metric: manhattan
Best Weights: distance

--- Default KNN Performance ---
Accuracy : 0.8649
Precision: 0.8449
Recall   : 0.8649
F1-score : 0.8480

--- Tuned KNN using GridSearchCV Performance ---
Accuracy : 0.8874
Precision: 0.8855
Recall   : 0.8874
F1-score : 0.8630