In [739]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, LabelEncoder

# 1. Diabetes Dataset – Missing Value Imputation & Encoding

In [740]:
df = pd.read_csv("/content/diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [741]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [742]:
col = ['Glucose', 'BloodPressure', 'BMI']
df[col] = df[col].replace(0, np.nan)
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35,0,33.6,0.627,50,1
1,1,85.0,66.0,29,0,26.6,0.351,31,0
2,8,183.0,64.0,0,0,23.3,0.672,32,1
3,1,89.0,66.0,23,94,28.1,0.167,21,0
4,0,137.0,40.0,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48,180,32.9,0.171,63,0
764,2,122.0,70.0,27,0,36.8,0.340,27,0
765,5,121.0,72.0,23,112,26.2,0.245,30,0
766,1,126.0,60.0,0,0,30.1,0.349,47,1
767,1,93.0,70.0,31,0,30.4,0.315,23,0

In [743]:
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer.fit(df[col])
df[col] = imputer.transform(df[col])
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35,0,33.6,0.627,50,1
1,1,85.0,66.0,29,0,26.6,0.351,31,0
2,8,183.0,64.0,0,0,23.3,0.672,32,1
3,1,89.0,66.0,23,94,28.1,0.167,21,0
4,0,137.0,40.0,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48,180,32.9,0.171,63,0
764,2,122.0,70.0,27,0,36.8,0.340,27,0
765,5,121.0,72.0,23,112,26.2,0.245,30,0
766,1,126.0,60.0,0,0,30.1,0.349,47,1
767,1,93.0,70.0,31,0,30.4,0.315,23,0

In [744]:
bins = [0, 29, 50, 150]
labels = ['Young', 'Adult', 'Senior']
df['Age_Group'] = pd.cut(df['Age'], bins=bins, labels=labels)
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Age_Group
0,6,148.0,72.0,35,0,33.6,0.627,50,1,Adult
1,1,85.0,66.0,29,0,26.6,0.351,31,0,Adult
2,8,183.0,64.0,0,0,23.3,0.672,32,1,Adult
3,1,89.0,66.0,23,94,28.1,0.167,21,0,Young
4,0,137.0,40.0,35,168,43.1,2.288,33,1,Adult
...,...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48,180,32.9,0.171,63,0,Senior
764,2,122.0,70.0,27,0,36.8,0.340,27,0,Young
765,5,121.0,72.0,23,112,26.2,0.245,30,0,Adult
766,1,126.0,60.0,0,0,30.1,0.349,47,1,Adult
767,1,93.0,70.0,31,0,30.4,0.315,23,0,Young

In [745]:
encoder = OrdinalEncoder(categories=[['Young', 'Adult', 'Senior']])
encoder.fit(df[['Age_Group']])
df['Age_Group_Encoded'] = encoder.transform(df[['Age_Group']])
df.shape

(768, 11)

# 2. Heart Disease Dataset – One Hot Encoding

In [746]:
 df = pd.read_csv("/content/heart.csv")
 df.head()
 df.shape

(1025, 14)

In [747]:
categorial_col = df.select_dtypes(include=['object', 'category'])
categorial_col

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1025 rows x 0 columns]

In [748]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [749]:
ohe_cp = OneHotEncoder(sparse_output=False, drop='first', dtype=int).set_output(transform='pandas')
ohe_cp.fit(df[['cp']])  # Step 1: Fit
cp_encoded = ohe_cp.transform(df[['cp']])
cp_encoded

      cp_1  cp_2  cp_3
0        0     0     0
1        0     0     0
2        0     0     0
3        0     0     0
4        0     0     0
...    ...   ...   ...
1020     1     0     0
1021     0     0     0
1022     0     0     0
1023     0     0     0
1024     0     0     0

[1025 rows x 3 columns]

In [750]:
ohe_thal = OneHotEncoder(sparse_output=False, drop='first', dtype=int).set_output(transform='pandas')
ohe_thal.fit(df[['thal']])  # Step 1: Fit
thal_encoded = ohe_thal.transform(df[['thal']])
thal_encoded

      thal_1  thal_2  thal_3
0          0       0       1
1          0       0       1
2          0       0       1
3          0       0       1
4          0       1       0
...      ...     ...     ...
1020       0       1       0
1021       0       0       1
1022       0       1       0
1023       0       1       0
1024       0       0       1

[1025 rows x 3 columns]

In [751]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [752]:
df = pd.concat([df, cp_encoded], axis=1)
df = pd.concat([df, thal_encoded], axis=1)
df.shape

(1025, 20)

# 3. Tips Dataset – Label Encoding

In [753]:
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [754]:
sex_lbl = LabelEncoder()
sex_lbl.fit(df[['sex']])
df['Encoded_sex'] = sex_lbl.transform(df[['sex']])
df.head()

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:93: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

   total_bill   tip     sex smoker  day    time  size  Encoded_sex
0       16.99  1.01  Female     No  Sun  Dinner     2            0
1       10.34  1.66    Male     No  Sun  Dinner     3            1
2       21.01  3.50    Male     No  Sun  Dinner     3            1
3       23.68  3.31    Male     No  Sun  Dinner     2            1
4       24.59  3.61  Female     No  Sun  Dinner     4            0

In [755]:
smoke_lbl = LabelEncoder()
smoke_lbl.fit(df[['smoker']])
df['Encoded_smoker'] = smoke_lbl.transform(df[['smoker']])
df.head()

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:93: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

,total_bill,tip,sex,smoker,day,time,size,Encoded_sex,Encoded_smoker
0,16.99,1.01,Female,No,Sun,Dinner,2,0,0
1,10.34,1.66,Male,No,Sun,Dinner,3,1,0
2,21.01,3.50,Male,No,Sun,Dinner,3,1,0
3,23.68,3.31,Male,No,Sun,Dinner,2,1,0
4,24.59,3.61,Female,No,Sun,Dinner,4,0,0

In [756]:
tips_bin = [0, 2.99, 6.0, float('inf')]
tips_category = ['Low', 'Medium', 'High']
df['tip_category'] = pd.cut(df['tip'], bins=tips_bin, labels=tips_category)
df

,total_bill,tip,sex,smoker,day,time,size,Encoded_sex,Encoded_smoker,tip_category
0,16.99,1.01,Female,No,Sun,Dinner,2,0,0,Low
1,10.34,1.66,Male,No,Sun,Dinner,3,1,0,Low
2,21.01,3.50,Male,No,Sun,Dinner,3,1,0,Medium
3,23.68,3.31,Male,No,Sun,Dinner,2,1,0,Medium
4,24.59,3.61,Female,No,Sun,Dinner,4,0,0,Medium
...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,1,0,Medium
240,27.18,2.00,Female,Yes,Sat,Dinner,2,0,1,Low
241,22.67,2.00,Male,Yes,Sat,Dinner,2,1,1,Low
242,17.82,1.75,Male,No,Sat,Dinner,2,1,0,Low
243,18.78,3.00,Female,No,Thur,Dinner,2,0,0,Medium

In [757]:
tip_encoded = OrdinalEncoder(categories=[tips_category])
tip_encoded.fit(df[['tip_category']])
df['tip_category_encoded'] = tip_encoded.transform(df[['tip_category']])
df.sample(10)

,total_bill,tip,sex,smoker,day,time,size,Encoded_sex,Encoded_smoker,tip_category,tip_category_encoded
74,14.73,2.20,Female,No,Sat,Dinner,2,0,0,Low,0.0
152,17.26,2.74,Male,No,Sun,Dinner,3,1,0,Low,0.0
53,9.94,1.56,Male,No,Sun,Dinner,2,1,0,Low,0.0
237,32.83,1.17,Male,Yes,Sat,Dinner,2,1,1,Low,0.0
36,16.31,2.00,Male,No,Sat,Dinner,3,1,0,Low,0.0
101,15.38,3.00,Female,Yes,Fri,Dinner,2,0,1,Medium,1.0
156,48.17,5.00,Male,No,Sun,Dinner,6,1,0,Medium,1.0
212,48.33,9.00,Male,No,Sat,Dinner,4,1,0,High,2.0
140,17.47,3.50,Female,No,Thur,Lunch,2,0,0,Medium,1.0
194,16.58,4.00,Male,Yes,Thur,Lunch,2,1,1,Medium,1.0

# 4. Car Price Dataset – Train/Test Encoding Pipeline

In [758]:
df = pd.read_csv("/content/CarPrice_Assignment.csv")
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [759]:
x = df.drop(['price', 'car_ID', 'CarName'], axis=1)
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [760]:
encoded_df = OneHotEncoder(categories=[['gas', 'diesel']], sparse_output=False, dtype=int)
encoded_df.fit(X_train[['fueltype']])

X_train_array = encoded_df.transform(X_train[['fueltype']])
X_test_array = encoded_df.transform(X_test[['fueltype']])

temp_X_train = pd.DataFrame(X_train_array, columns=encoded_df.get_feature_names_out(['fueltype']), index=X_train.index)
temp_X_test = pd.DataFrame(X_test_array, columns=encoded_df.get_feature_names_out(['fueltype']), index=X_test.index)

X_train = pd.concat([X_train.drop('fueltype', axis=1), temp_X_train], axis=1)
X_test = pd.concat([X_test.drop('fueltype', axis=1), temp_X_test], axis=1)

In [761]:
ohe_drive = OneHotEncoder(sparse_output=False, drop='first', dtype='int')
ohe_drive.fit(X_train[['drivewheel']])

X_train_array = ohe_drive.transform(X_train[['drivewheel']])
X_test_array = ohe_drive.transform(X_test[['drivewheel']])

X_train_temp = pd.DataFrame(X_train_array, columns=ohe_drive.get_feature_names_out(['drivewheel']), index=X_train.index)
X_test_temp = pd.DataFrame(X_test_array, columns=ohe_drive.get_feature_names_out(['drivewheel']), index=X_test.index)


X_train = pd.concat([X_train.drop(['drivewheel'], axis=1), X_train_temp], axis=1)
X_test = pd.concat(
    [ X_test.drop(['drivewheel'], axis=1), X_test ],
    axis=1
)

X_test

,symboling,aspiration,doornumber,carbody,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,...,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,fueltype_gas,fueltype_diesel
15,0,std,four,sedan,front,103.5,189.0,66.9,55.7,3230,...,mpfi,3.62,3.390,8.00,182,5400,16,22,1,0
9,0,turbo,two,hatchback,front,99.5,178.2,67.9,52.0,3053,...,mpfi,3.13,3.400,7.00,160,5500,16,22,1,0
100,0,std,four,sedan,front,97.2,173.4,65.2,54.7,2302,...,2bbl,3.33,3.470,8.50,97,5200,27,34,1,0
132,3,std,two,hatchback,front,99.1,186.6,66.5,56.1,2658,...,mpfi,3.54,3.070,9.31,110,5250,21,28,1,0
68,-1,turbo,four,wagon,front,110.0,190.9,70.3,58.7,3750,...,idi,3.58,3.640,21.50,123,4350,22,25,0,1
95,1,std,two,hatchback,front,94.5,165.6,63.8,53.3,2028,...,2bbl,3.15,3.290,9.40,69,5200,31,37,1,0
159,0,std,four,hatchback,front,95.7,166.3,64.4,52.8,2275,...,idi,3.27,3.350,22.50,56,4500,38,47,0,1
162,0,std,four,sedan,front,95.7,166.3,64.4,52.8,2140,...,2bbl,3.19,3.030,9.00,70,4800,28,34,1,0
147,0,std,four,wagon,front,97.0,173.5,65.4,53.0,2455,...,mpfi,3.62,2.640,9.00,94,5200,25,31,1,0
182,2,std,two,sedan,front,97.3,171.7,65.5,55.7,2261,...,idi,3.01,3.400,23.00,52,4800,37,46,0,1
191,0,std,four,sedan,front,100.4,180.2,66.9,55.1,2661,...,mpfi,3.19,3.400,8.50,110,5500,19,24,1,0
164,1,std,two,hatchback,front,94.5,168.7,64.0,52.6,2204,...,2bbl,3.19,3.030,9.00,70,4800,29,34,1,0
65,0,std,four,sedan,front,104.9,175.0,66.1,54.4,2670,...,mpfi,3.76,3.160,8.00,120,5000,19,27,1,0
175,-1,std,four,hatchback,front,102.4,175.6,66.5,53.9,2414,...,mpfi,3.31,3.540,8.70,92,4200,27,32,1,0
73,0,std,four,sedan,front,120.9,208.1,71.7,56.7,3900,...,mpfi,3.80,3.350,8.00,184,4500,14,16,1,0
152,1,std,four,hatchback,front,95.7,158.7,63.6,54.5,2015,...,2bbl,3.05,3.030,9.00,62,4800,31,38,1,0
18,2,std,two,hatchback,front,88.4,141.1,60.3,53.2,1488,...,2bbl,2.91,3.030,9.50,48,5100,47,53,1,0
82,3,turbo,two,hatchback,front,95.9,173.2,66.3,50.2,2833,...,spdi,3.58,3.860,7.00,145,5000,19,24,1,0
86,1,std,four,sedan,front,96.3,172.4,65.4,51.6,2405,...,2bbl,3.35,3.460,8.50,88,5000,25,32,1,0
143,0,std,four,sedan,front,97.2,172.0,65.4,52.5,2340,...,mpfi,3.62,2.640,9.00,94,5200,26,32,1,0
60,0,std,four,sedan,front,98.8,177.8,66.5,55.5,2410,...,2bbl,3.39,3.390,8.60,84,4800,26,32,1,0
101,0,std,four,sedan,front,100.4,181.7,66.5,55.1,3095,...,mpfi,3.43,3.270,9.00,152,5200,17,22,1,0
98,2,std,two,hardtop,front,95.1,162.4,63.8,53.3,2008,...,2bbl,3.15,3.290,9.40,69,5200,31,37,1,0
30,2,std,two,hatchback,front,86.6,144.6,63.9,50.8,1713,...,1bbl,2.91,3.410,9.60,58,4800,49,54,1,0
25,1,std,four,sedan,front,93.7,157.3,63.8,50.6,1989,...,2bbl,2.97,3.230,9.40,68,5500,31,38,1,0
16,0,std,two,sedan,front,103.5,193.8,67.9,53.7,3380,...,mpfi,3.62,3.390,8.00,182,5400,16,22,1,0
168,2,std,two,hardtop,front,98.4,176.2,65.6,52.0,2536,...,mpfi,3.62,3.500,9.30,116,4800,24,30,1,0
195,-1,std,four,wagon,front,104.3,188.8,67.2,57.5,3034,...,mpfi,3.78,3.150,9.50,114,5400,23,28,1,0
97,1,std,four,wagon,front,94.5,170.2,63.8,53.5,2037,...,2bbl,3.15,3.290,9.40,69,5200,31,37,1,0
194,-2,std,four,sedan,front,104.3,188.8,67.2,56.2,2912,...,mpfi,3.78,3.150,9.50,114,5400,23,28,1,0
67,-1,turbo,four,sedan,front,110.0,190.9,70.3,56.5,3515,...,idi,3.58,3.640,21.50,123,4350,22,25,0,1
120,1,std,four,hatchback,front,93.7,157.3,63.8,50.6,1967,...,2bbl,2.97,3.230,9.40,68,5500,31,38,1,0
154,0,std,four,wagon,front,95.7,169.7,63.6,59.1,2290,...,2bbl,3.05,3.030,9.00,62,4800,27,32,1,0
202,-1,std,four,sedan,front,109.1,188.8,68.9,55.5,3012,...,mpfi,3.58,2.870,8.80,134,5500,18,23,1,0
79,1,turbo,two,hatchback,front,93.0,157.3,63.8,50.8,2145,...,spdi,3.03,3.390,7.60,102,5500,24,30,1,0
69,0,turbo,two,hardtop,front,106.7,187.5,70.3,54.9,3495,...,idi,3.58,3.640,21.50,123,4350,22,25,0,1
145,0,turbo,four,sedan,front,97.0,172.0,65.4,54.3,2510,...,mpfi,3.62,2.640,7.70,111,4800,24,29,1,0
55,3,std,two,hatchback,front,95.3,169.0,65.7,49.6,2380,...,4bbl,3.33,3.255,9.40,101,6000,17,23,1,0
45,0,std,four,sedan,front,94.5,155.9,63.6,52.0,1909,...,2bbl,3.03,3.110,9.60,70,5400,38,43,1,0
84,3,turbo,two,hatchback,front,95.9,173.2,66.3,50.2,2926,...,spdi,3.59,3.860,7.00,145,5000,19,24,1,0
146,0,std,four,wagon,front,97.0,173.5,65.4,53.0,2290,...,2bbl,3.62,2.640,9.00,82,4800,28,32,1,0

# Optional